### ISSUE TITLE
Publish on Docker Hub

### ISSUE THREAD

**Issue by mstockd** [shreddedbacon/concourse-slackbot#1]
Hey, nice project!

It would be very convenient if you could publish releases of the built image to docker hub - is that something you'd consider adding?

**Comment by shreddedbacon** [comment]
Sure, I can get that done. Will let you know when its ready @mstockd

**Comment by mstockd** [comment]
Thanks a lot! :)

**Comment by shreddedbacon** [comment]
@mstockd done
https://hub.docker.com/r/shreddedbacon/concoursebot/tags
